### ISSUE TITLE
Newer version throws error

### ISSUE THREAD

**Issue by ghost** [Ralith/riot-electron-nix#1]
Using v0.11.3
https://github.com/unlmtd/riot-electron-nix/tree/v0.11.3

Upon launch I get 
``` javascript
App threw an error during load
Error: Cannot find module 'minimist'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/nix/store/gdsscmjbp9py8wdx6by4adg1yc9g0zxf-electron-1.6.6/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:
12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/nix/store/mz4wqvsj0dy64c2c7phybjgnjvcxrwh3-riot-desktop-0.11.3/electron_app/src/electron-main.js:25:14)
    at Object.<anonymous> (/nix/store/mz4wqvsj0dy64c2c7phybjgnjvcxrwh3-riot-desktop-0.11.3/electron_app/src/electron-main.js:314:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'minimist'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/nix/store/gdsscmjbp9py8wdx6by4adg1yc9g0zxf-electron-1.6.6/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:
12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/nix/store/mz4wqvsj0dy64c2c7phybjgnjvcxrwh3-riot-desktop-0.11.3/electron_app/src/electron-main.js:25:14)
    at Object.<anonymous> (/nix/store/mz4wqvsj0dy64c2c7phybjgnjvcxrwh3-riot-desktop-0.11.3/electron_app/src/electron-main.js:314:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by Ralith** [comment]
Not a bug in this repository.

**Comment by ghost** [comment]
So you know where the problem lies then?
